apiVersion: v1
kind: Secret
metadata:
  name: credential-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: https://github.com/m0hadang # no need to specify repo
  username: argocd-private-key # registered token key name
  password: <<input github personal token(can find developer settings)>> 
