apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: restrict-project
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  # allow only dev namespace
  # - namespace: 'dev'

  # block only dev namespace
  - namespace: '!dev'
    server: '*'
  sourceRepos:
  - '*'
