apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-directory
spec:
  destination:
    namespace: directory
    server: https://kubernetes.default.svc
  project: default
  source: 
    directory:
      include: '{serviceaccount.yml,service.yml}' # include only these. !! don't insert space !!
    path: directory-of-manifests
    repoURL: https://github.com/m0hadang/test-argocd.git
    targetRevision: main
